function [Absorption]=Lumlink(Height_Sio2,height_teeth,teeth_num,width_ratio,uni);

path(path,'C:\Program Files\Lumerical\FDTD\bin\matlab');  %add Lumerical API path to Matlab; 
h=appopen('fdtd');
appevalscript(h,'load("Grating_PSO_optimization.fsp");');


code=strcat('switchtolayout;',...
    'deleteall;',...
    'startpoint=0;',...
    'Height_Gold=0.1e-6;',...
    'Height_Spiro=0.05e-6;',...
    'Height_Pero=0.6e-6;',...
    'Height_TiO2=0.05e-6;',...
    'Height_ITO=0.05e-6; wavelength_start=0.38e-6;wavelength_stop=0.8e-6; Height_SiO2=',num2str(abs(Height_Sio2)),';',...
    'Height_grating=',num2str(abs(height_teeth)),';',...
    'gratingNumber=',num2str(abs(teeth_num)),';',...
    'ratio=',num2str(abs(width_ratio)),';',...
    'nonuni=',num2str(abs(uni)),';',...
    'max_gold=startpoint+Height_Gold;',...
    'max_spiro=max_gold+Height_Spiro;',...
    'max_pero=max_spiro+Height_Pero;',...
    'max_tio2=max_pero+Height_TiO2;',...
    'max_ito=max_tio2+Height_ITO;',...
    'max_sio2=max_ito+Height_SiO2;',...
    'addrect; set("name","Conductor");  set("material", "GOLD FINAL");',...
    'set("x min", -0.5e-6);       set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6);              set("y max", 0.5e-6);',...
    'set("z min", startpoint);          set("z max",Height_Gold);',...
    'addrect; set("name","Spiro");  set("material", "Spiro");',...
    'set("x min", -0.5e-6);       set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6);              set("y max", 0.5e-6);',...
    'set("z min", Height_Gold);          set("z max", max_spiro);',...
    'addrect; set("name","Perovskite");  set("material", "Perovskite 2");',...
    'set("x min", -0.5e-6);       set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6);              set("y max", 0.5e-6);',...
    'set("z min", max_spiro);          set("z max", max_pero);',...
    'addrect; set("name","TiO2");  set("material", "TiO2");',...
    'set("x min", -0.5e-6);       set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6);              set("y max", 0.5e-6);',...
    'set("z min", max_pero);          set("z max", max_tio2);',...
    'addrect; set("name","ITO");  set("material", "ITO");',...
    'set("x min", -0.5e-6);       set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6);              set("y max", 0.5e-6);',...
    'set("z min", max_tio2);          set("z max", max_ito);',...
    'addrect; set("name","SiO2");  set("material", "SiO2 (Glass) - Palik");',...
    'set("x min", -0.5e-6);       set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6);              set("y max", 0.5e-6);',...
    'set("z min", max_ito);          set("z max", max_sio2);',...
    'addfdtd; set("mesh accuracy", 2);',...
    'set("x min", -0.5e-6); set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6); set("y max", 0.5e-6);',...
    'set("z min", startpoint);  set("z max", max_sio2+Height_grating+0.7e-6);',...
    'addpower;',...
    'set("name", "R");',...
    'set("monitor type", "2D Z-normal");',...
    'set("y min", -0.5e-6);  set("y max", 0.5e-6);',...
    'set("x min", -0.5e-6);  set("x max", 0.5e-6);',...
    'set("z",max_pero ); ',...
    'addpower; set("name", "T");',...
    'set("monitor type", "2D Z-normal");',...
    'set("y min", -0.5e-6);  set("y max", 0.5e-6);',...
    'set("x min", -0.5e-6);  set("x max", 0.5e-6);',...
    'set("z",max_spiro ); ',...
    'addplane; set("injection axis", "z-axis");',...
    'set("direction", "backward");',...
    'set("x min", -0.5e-6); set("x max", 0.5e-6);',...
    'set("y min", -0.5e-6); set("y max", 0.5e-6);',...
    'set("z", max_sio2+Height_grating+0.4e-6); ',...
    'set("set wavelength",1);',...
    'set("wavelength start", wavelength_start); ',...
    'set("wavelength stop",wavelength_stop); ',...
    'for(i=1:gratingNumber){ gap=(1e-6)/(ratio*(1+(i-1)*nonuni)*gratingNumber);',...
    'period=(1+(i-1)*nonuni)*ratio*gap;',...
    'addrect; ',...
    'set("name","GC_tooth");',...
    'set("material","SiO2 (Glass) - Palik");',...
    'XMIN=(-0.5e-6)+gap+(i-1)*period;',...
    'XMAX=(-0.5e-6)+period+(i-1)*period;',...
    'if(XMAX>0.5e-6){ XMAX=0.5e-6;  }',...
    'set("x min",XMIN); set("x max",XMAX);',...
    'set("y min",-0.5e-6); set("y max",0.5e-6);',...
    'set("z min",max_sio2); set("z max",max_sio2+Height_grating);}',...
    'selectpartial("GC");',...
    'addtogroup("GC");');
appevalscript(h,code);

appevalscript(h,'run;');
appevalscript(h,'R=abs(transmission("R"));');
appevalscript(h,'T=abs(transmission("T"));');
R=appgetvar(h,'R');
T=appgetvar(h,'T');
Abs=R-T;
Absorption= mean(Abs,"all");

appclose(h);
end 



% appevalscript(h,'T=T.T;');
%appclose(h);

%appclose(h);

